#!/bin/bash -e

if [ ! -f $ELASTICSEARCH_HOME/.esconfig ]; then
    if [ "$MASTER_IP" = "" ] ; then
        MASTER_IP=$(/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')
        IS_MASTER=true
    else
        IS_MASTER=false
    fi

    CONF_FILE=$ELASTICSEARCH_HOME/config/elasticsearch.yml
    echo "node.master: $IS_MASTER" >> $CONF_FILE
    echo "discovery.zen.ping.multicast.enabled: false" >> $CONF_FILE
    echo "discovery.zen.ping.unicast.hosts: [\"$MASTER_IP\"]" >> $CONF_FILE

    $ELASTICSEARCH_HOME/bin/plugin -install elasticsearch/marvel/latest

    touch $ELASTICSEARCH_HOME/.esconfig
fi

# Check if overrides were provided
export ES_HEAP_SIZE=${ES_HEAP_SIZE:="1g"}

$ELASTICSEARCH_HOME/bin/elasticsearch
